# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rmep_msgs/GimbalFdb.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class GimbalFdb(genpy.Message):
  _md5sum = "4baddb8bc789a9d0d6c754f66cd82965"
  _type = "rmep_msgs/GimbalFdb"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
float32 pitch_angle_fdb
float32 yaw_angle_fdb
float32 pitch_ground_angle_fdb
float32 yaw_ground_angle_fdb


"""
  __slots__ = ['stamp','pitch_angle_fdb','yaw_angle_fdb','pitch_ground_angle_fdb','yaw_ground_angle_fdb']
  _slot_types = ['time','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,pitch_angle_fdb,yaw_angle_fdb,pitch_ground_angle_fdb,yaw_ground_angle_fdb

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GimbalFdb, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.pitch_angle_fdb is None:
        self.pitch_angle_fdb = 0.
      if self.yaw_angle_fdb is None:
        self.yaw_angle_fdb = 0.
      if self.pitch_ground_angle_fdb is None:
        self.pitch_ground_angle_fdb = 0.
      if self.yaw_ground_angle_fdb is None:
        self.yaw_ground_angle_fdb = 0.
    else:
      self.stamp = genpy.Time()
      self.pitch_angle_fdb = 0.
      self.yaw_angle_fdb = 0.
      self.pitch_ground_angle_fdb = 0.
      self.yaw_ground_angle_fdb = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I4f().pack(_x.stamp.secs, _x.stamp.nsecs, _x.pitch_angle_fdb, _x.yaw_angle_fdb, _x.pitch_ground_angle_fdb, _x.yaw_ground_angle_fdb))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.stamp.secs, _x.stamp.nsecs, _x.pitch_angle_fdb, _x.yaw_angle_fdb, _x.pitch_ground_angle_fdb, _x.yaw_ground_angle_fdb,) = _get_struct_2I4f().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I4f().pack(_x.stamp.secs, _x.stamp.nsecs, _x.pitch_angle_fdb, _x.yaw_angle_fdb, _x.pitch_ground_angle_fdb, _x.yaw_ground_angle_fdb))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.stamp.secs, _x.stamp.nsecs, _x.pitch_angle_fdb, _x.yaw_angle_fdb, _x.pitch_ground_angle_fdb, _x.yaw_ground_angle_fdb,) = _get_struct_2I4f().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I4f = None
def _get_struct_2I4f():
    global _struct_2I4f
    if _struct_2I4f is None:
        _struct_2I4f = struct.Struct("<2I4f")
    return _struct_2I4f
