// Generated by gencpp from file rmep_msgs/GimbalFdb.msg
// DO NOT EDIT!


#ifndef RMEP_MSGS_MESSAGE_GIMBALFDB_H
#define RMEP_MSGS_MESSAGE_GIMBALFDB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rmep_msgs
{
template <class ContainerAllocator>
struct GimbalFdb_
{
  typedef GimbalFdb_<ContainerAllocator> Type;

  GimbalFdb_()
    : stamp()
    , pitch_angle_fdb(0.0)
    , yaw_angle_fdb(0.0)
    , pitch_ground_angle_fdb(0.0)
    , yaw_ground_angle_fdb(0.0)  {
    }
  GimbalFdb_(const ContainerAllocator& _alloc)
    : stamp()
    , pitch_angle_fdb(0.0)
    , yaw_angle_fdb(0.0)
    , pitch_ground_angle_fdb(0.0)
    , yaw_ground_angle_fdb(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef float _pitch_angle_fdb_type;
  _pitch_angle_fdb_type pitch_angle_fdb;

   typedef float _yaw_angle_fdb_type;
  _yaw_angle_fdb_type yaw_angle_fdb;

   typedef float _pitch_ground_angle_fdb_type;
  _pitch_ground_angle_fdb_type pitch_ground_angle_fdb;

   typedef float _yaw_ground_angle_fdb_type;
  _yaw_ground_angle_fdb_type yaw_ground_angle_fdb;





  typedef boost::shared_ptr< ::rmep_msgs::GimbalFdb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rmep_msgs::GimbalFdb_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalFdb_

typedef ::rmep_msgs::GimbalFdb_<std::allocator<void> > GimbalFdb;

typedef boost::shared_ptr< ::rmep_msgs::GimbalFdb > GimbalFdbPtr;
typedef boost::shared_ptr< ::rmep_msgs::GimbalFdb const> GimbalFdbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rmep_msgs::GimbalFdb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rmep_msgs::GimbalFdb_<ContainerAllocator1> & lhs, const ::rmep_msgs::GimbalFdb_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.pitch_angle_fdb == rhs.pitch_angle_fdb &&
    lhs.yaw_angle_fdb == rhs.yaw_angle_fdb &&
    lhs.pitch_ground_angle_fdb == rhs.pitch_ground_angle_fdb &&
    lhs.yaw_ground_angle_fdb == rhs.yaw_ground_angle_fdb;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rmep_msgs::GimbalFdb_<ContainerAllocator1> & lhs, const ::rmep_msgs::GimbalFdb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rmep_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rmep_msgs::GimbalFdb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rmep_msgs::GimbalFdb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rmep_msgs::GimbalFdb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4baddb8bc789a9d0d6c754f66cd82965";
  }

  static const char* value(const ::rmep_msgs::GimbalFdb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4baddb8bc789a9d0ULL;
  static const uint64_t static_value2 = 0xd6c754f66cd82965ULL;
};

template<class ContainerAllocator>
struct DataType< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rmep_msgs/GimbalFdb";
  }

  static const char* value(const ::rmep_msgs::GimbalFdb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float32 pitch_angle_fdb\n"
"float32 yaw_angle_fdb\n"
"float32 pitch_ground_angle_fdb\n"
"float32 yaw_ground_angle_fdb\n"
"\n"
"\n"
;
  }

  static const char* value(const ::rmep_msgs::GimbalFdb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.pitch_angle_fdb);
      stream.next(m.yaw_angle_fdb);
      stream.next(m.pitch_ground_angle_fdb);
      stream.next(m.yaw_ground_angle_fdb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalFdb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rmep_msgs::GimbalFdb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rmep_msgs::GimbalFdb_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "pitch_angle_fdb: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_angle_fdb);
    s << indent << "yaw_angle_fdb: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_angle_fdb);
    s << indent << "pitch_ground_angle_fdb: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_ground_angle_fdb);
    s << indent << "yaw_ground_angle_fdb: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_ground_angle_fdb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RMEP_MSGS_MESSAGE_GIMBALFDB_H
