// Generated by gencpp from file rmep_msgs/RobotBlaster.msg
// DO NOT EDIT!


#ifndef RMEP_MSGS_MESSAGE_ROBOTBLASTER_H
#define RMEP_MSGS_MESSAGE_ROBOTBLASTER_H

#include <ros/service_traits.h>


#include <rmep_msgs/RobotBlasterRequest.h>
#include <rmep_msgs/RobotBlasterResponse.h>


namespace rmep_msgs
{

struct RobotBlaster
{

typedef RobotBlasterRequest Request;
typedef RobotBlasterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotBlaster
} // namespace rmep_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rmep_msgs::RobotBlaster > {
  static const char* value()
  {
    return "a7120ebecfd35f623ffd5d4687655fe9";
  }

  static const char* value(const ::rmep_msgs::RobotBlaster&) { return value(); }
};

template<>
struct DataType< ::rmep_msgs::RobotBlaster > {
  static const char* value()
  {
    return "rmep_msgs/RobotBlaster";
  }

  static const char* value(const ::rmep_msgs::RobotBlaster&) { return value(); }
};


// service_traits::MD5Sum< ::rmep_msgs::RobotBlasterRequest> should match
// service_traits::MD5Sum< ::rmep_msgs::RobotBlaster >
template<>
struct MD5Sum< ::rmep_msgs::RobotBlasterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rmep_msgs::RobotBlaster >::value();
  }
  static const char* value(const ::rmep_msgs::RobotBlasterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmep_msgs::RobotBlasterRequest> should match
// service_traits::DataType< ::rmep_msgs::RobotBlaster >
template<>
struct DataType< ::rmep_msgs::RobotBlasterRequest>
{
  static const char* value()
  {
    return DataType< ::rmep_msgs::RobotBlaster >::value();
  }
  static const char* value(const ::rmep_msgs::RobotBlasterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rmep_msgs::RobotBlasterResponse> should match
// service_traits::MD5Sum< ::rmep_msgs::RobotBlaster >
template<>
struct MD5Sum< ::rmep_msgs::RobotBlasterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rmep_msgs::RobotBlaster >::value();
  }
  static const char* value(const ::rmep_msgs::RobotBlasterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmep_msgs::RobotBlasterResponse> should match
// service_traits::DataType< ::rmep_msgs::RobotBlaster >
template<>
struct DataType< ::rmep_msgs::RobotBlasterResponse>
{
  static const char* value()
  {
    return DataType< ::rmep_msgs::RobotBlaster >::value();
  }
  static const char* value(const ::rmep_msgs::RobotBlasterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMEP_MSGS_MESSAGE_ROBOTBLASTER_H
