// Generated by gencpp from file rmep_msgs/RobotArm.msg
// DO NOT EDIT!


#ifndef RMEP_MSGS_MESSAGE_ROBOTARM_H
#define RMEP_MSGS_MESSAGE_ROBOTARM_H

#include <ros/service_traits.h>


#include <rmep_msgs/RobotArmRequest.h>
#include <rmep_msgs/RobotArmResponse.h>


namespace rmep_msgs
{

struct RobotArm
{

typedef RobotArmRequest Request;
typedef RobotArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotArm
} // namespace rmep_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rmep_msgs::RobotArm > {
  static const char* value()
  {
    return "ca73bd755846e340fdd096df095b3706";
  }

  static const char* value(const ::rmep_msgs::RobotArm&) { return value(); }
};

template<>
struct DataType< ::rmep_msgs::RobotArm > {
  static const char* value()
  {
    return "rmep_msgs/RobotArm";
  }

  static const char* value(const ::rmep_msgs::RobotArm&) { return value(); }
};


// service_traits::MD5Sum< ::rmep_msgs::RobotArmRequest> should match
// service_traits::MD5Sum< ::rmep_msgs::RobotArm >
template<>
struct MD5Sum< ::rmep_msgs::RobotArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rmep_msgs::RobotArm >::value();
  }
  static const char* value(const ::rmep_msgs::RobotArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmep_msgs::RobotArmRequest> should match
// service_traits::DataType< ::rmep_msgs::RobotArm >
template<>
struct DataType< ::rmep_msgs::RobotArmRequest>
{
  static const char* value()
  {
    return DataType< ::rmep_msgs::RobotArm >::value();
  }
  static const char* value(const ::rmep_msgs::RobotArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rmep_msgs::RobotArmResponse> should match
// service_traits::MD5Sum< ::rmep_msgs::RobotArm >
template<>
struct MD5Sum< ::rmep_msgs::RobotArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rmep_msgs::RobotArm >::value();
  }
  static const char* value(const ::rmep_msgs::RobotArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmep_msgs::RobotArmResponse> should match
// service_traits::DataType< ::rmep_msgs::RobotArm >
template<>
struct DataType< ::rmep_msgs::RobotArmResponse>
{
  static const char* value()
  {
    return DataType< ::rmep_msgs::RobotArm >::value();
  }
  static const char* value(const ::rmep_msgs::RobotArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMEP_MSGS_MESSAGE_ROBOTARM_H
