// Generated by gencpp from file rmep_msgs/RobotGrip.msg
// DO NOT EDIT!


#ifndef RMEP_MSGS_MESSAGE_ROBOTGRIP_H
#define RMEP_MSGS_MESSAGE_ROBOTGRIP_H

#include <ros/service_traits.h>


#include <rmep_msgs/RobotGripRequest.h>
#include <rmep_msgs/RobotGripResponse.h>


namespace rmep_msgs
{

struct RobotGrip
{

typedef RobotGripRequest Request;
typedef RobotGripResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotGrip
} // namespace rmep_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rmep_msgs::RobotGrip > {
  static const char* value()
  {
    return "156b17ddf1dc4e8bbde7e72d0e8736d5";
  }

  static const char* value(const ::rmep_msgs::RobotGrip&) { return value(); }
};

template<>
struct DataType< ::rmep_msgs::RobotGrip > {
  static const char* value()
  {
    return "rmep_msgs/RobotGrip";
  }

  static const char* value(const ::rmep_msgs::RobotGrip&) { return value(); }
};


// service_traits::MD5Sum< ::rmep_msgs::RobotGripRequest> should match
// service_traits::MD5Sum< ::rmep_msgs::RobotGrip >
template<>
struct MD5Sum< ::rmep_msgs::RobotGripRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rmep_msgs::RobotGrip >::value();
  }
  static const char* value(const ::rmep_msgs::RobotGripRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmep_msgs::RobotGripRequest> should match
// service_traits::DataType< ::rmep_msgs::RobotGrip >
template<>
struct DataType< ::rmep_msgs::RobotGripRequest>
{
  static const char* value()
  {
    return DataType< ::rmep_msgs::RobotGrip >::value();
  }
  static const char* value(const ::rmep_msgs::RobotGripRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rmep_msgs::RobotGripResponse> should match
// service_traits::MD5Sum< ::rmep_msgs::RobotGrip >
template<>
struct MD5Sum< ::rmep_msgs::RobotGripResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rmep_msgs::RobotGrip >::value();
  }
  static const char* value(const ::rmep_msgs::RobotGripResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmep_msgs::RobotGripResponse> should match
// service_traits::DataType< ::rmep_msgs::RobotGrip >
template<>
struct DataType< ::rmep_msgs::RobotGripResponse>
{
  static const char* value()
  {
    return DataType< ::rmep_msgs::RobotGrip >::value();
  }
  static const char* value(const ::rmep_msgs::RobotGripResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMEP_MSGS_MESSAGE_ROBOTGRIP_H
