// Generated by gencpp from file rmep_msgs/RobotPwm.msg
// DO NOT EDIT!


#ifndef RMEP_MSGS_MESSAGE_ROBOTPWM_H
#define RMEP_MSGS_MESSAGE_ROBOTPWM_H

#include <ros/service_traits.h>


#include <rmep_msgs/RobotPwmRequest.h>
#include <rmep_msgs/RobotPwmResponse.h>


namespace rmep_msgs
{

struct RobotPwm
{

typedef RobotPwmRequest Request;
typedef RobotPwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotPwm
} // namespace rmep_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rmep_msgs::RobotPwm > {
  static const char* value()
  {
    return "6c239c834ae059903d50c5af0762999e";
  }

  static const char* value(const ::rmep_msgs::RobotPwm&) { return value(); }
};

template<>
struct DataType< ::rmep_msgs::RobotPwm > {
  static const char* value()
  {
    return "rmep_msgs/RobotPwm";
  }

  static const char* value(const ::rmep_msgs::RobotPwm&) { return value(); }
};


// service_traits::MD5Sum< ::rmep_msgs::RobotPwmRequest> should match
// service_traits::MD5Sum< ::rmep_msgs::RobotPwm >
template<>
struct MD5Sum< ::rmep_msgs::RobotPwmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rmep_msgs::RobotPwm >::value();
  }
  static const char* value(const ::rmep_msgs::RobotPwmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmep_msgs::RobotPwmRequest> should match
// service_traits::DataType< ::rmep_msgs::RobotPwm >
template<>
struct DataType< ::rmep_msgs::RobotPwmRequest>
{
  static const char* value()
  {
    return DataType< ::rmep_msgs::RobotPwm >::value();
  }
  static const char* value(const ::rmep_msgs::RobotPwmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rmep_msgs::RobotPwmResponse> should match
// service_traits::MD5Sum< ::rmep_msgs::RobotPwm >
template<>
struct MD5Sum< ::rmep_msgs::RobotPwmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rmep_msgs::RobotPwm >::value();
  }
  static const char* value(const ::rmep_msgs::RobotPwmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rmep_msgs::RobotPwmResponse> should match
// service_traits::DataType< ::rmep_msgs::RobotPwm >
template<>
struct DataType< ::rmep_msgs::RobotPwmResponse>
{
  static const char* value()
  {
    return DataType< ::rmep_msgs::RobotPwm >::value();
  }
  static const char* value(const ::rmep_msgs::RobotPwmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMEP_MSGS_MESSAGE_ROBOTPWM_H
