(cl:defpackage rmep_msgs-srv
  (:use )
  (:export
   "ROBOTARM"
   "<ROBOTARM-REQUEST>"
   "ROBOTARM-REQUEST"
   "<ROBOTARM-RESPONSE>"
   "ROBOTARM-RESPONSE"
   "ROBOTBLASTER"
   "<ROBOTBLASTER-REQUEST>"
   "ROBOTBLASTER-REQUEST"
   "<ROBOTBLASTER-RESPONSE>"
   "ROBOTBLASTER-RESPONSE"
   "ROBOTGRIP"
   "<ROBOTGRIP-REQUEST>"
   "ROBOTGRIP-REQUEST"
   "<ROBOTGRIP-RESPONSE>"
   "ROBOTGRIP-RESPONSE"
   "ROBOTPWM"
   "<ROBOTPWM-REQUEST>"
   "ROBOTPWM-REQUEST"
   "<ROBOTPWM-RESPONSE>"
   "ROBOTPWM-RESPONSE"
  ))

